input.onButtonPressed(Button.A, function () {
    basic.showIcon(IconNames.Happy)
})
input.onButtonPressed(Button.B, function () {
    basic.showIcon(IconNames.Sad)
})
basic.showString("LISTEN")
music.setVolume(90)
music.playTone(880, music.beat(BeatFraction.Whole))
music.playTone(880, music.beat(BeatFraction.Eighth))
music.playTone(988, music.beat(BeatFraction.Whole))
music.playTone(988, music.beat(BeatFraction.Eighth))
music.playTone(784, music.beat(BeatFraction.Whole))
music.playTone(784, music.beat(BeatFraction.Quarter))
music.playTone(392, music.beat(BeatFraction.Whole))
music.playTone(392, music.beat(BeatFraction.Eighth))
music.playTone(587, music.beat(BeatFraction.Breve))
basic.showString("A=")
basic.showString("CLOSE ENCOUNTERS")
basic.showString("B=")
basic.showString("E.T.")
